name: ProsperBolt
favicon: null
layout_spectrum: 0.7762636533007026
typography_spectrum: 0.8300582920201123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6763728312216699
  lightness: 0.37752694729715586
  saturation: 0.5695238674525172
  rhythmicContrast: 0.926728866295889
purpose: []
